package supermarket.algorithms;

import supermarket.inventory.Product;
import supermarket.inventory.Activity;
import java.util.ArrayList;
import supermarket.management.CustomLinkedList;

// This class provides two insertion sort implementations used within the supermarket system.
//
// The first method sorts Product objects by their Product ID, ensuring the product list remains
// in sorted order so that the binary search algorithm can operate correctly.
//
// The second method sorts Activity objects by their quantity value, which is required when displaying the last
// four activities for a product in sorted order.
//
// Both sorting methods use the insertion sort
// technique, which is efficient and suitable for the small datasets generated by this project.


public class SortAlgorithm {

    // 1. INSERTION SORT FOR PRODUCT IDs
    //    This method keeps the product list sorted by their ID values.
    //    Binary search requires the list to be in sorted order, so this
    //    sorting method is called whenever new products are added.

    // Insertion sort defined
    // List consists of ProductIDs from the product class
    public static void insertionSortProductsByID(ArrayList<Product> products) {

        // Start from index 1 because index 0 is already "sorted" by itself
        for (int i = 1; i < products.size(); i++) {

            // Store the current product as the "key" to insert into position
            Product key = products.get(i);

            // j tracks the index before i, moving backwards
            int j = i - 1;

            // Shift all products with IDs greater than the key to the right
            while (j >= 0 && products.get(j).getId().compareTo(key.getId()) > 0) {
                products.set(j + 1, products.get(j));
                j--;
            }

            // Insert the key product into the correct sorted position
            products.set(j + 1, key);

        }
    }

    // 2. INSERTION SORT FOR ACTIVITY QUANTITIES
    //    This method sorts the last four activities of a product based on
    //    the quantity of items added or removed. The coursework requires
    //    displaying these activities in sorted order.

    // Insertion sort defined
    // List consists of Activity objects from the Activity class
    public static void insertionSortActivitiesByQuantity(CustomLinkedList<Activity> activities) {

        // Loop through the list starting from index 1
        for (int i = 1; i < activities.size(); i++) {

            // Store the current activity as the "key" item
            Activity key = activities.get(i);

            // j starts at the element before i
            int j = i - 1;

            // Shift activities with larger quantities to the right
            while (j >= 0 && activities.get(j).getQuantity() > key.getQuantity()) {
                activities.set(j + 1, activities.get(j));
                j--;
            }

            // Insert the "key" activity into the correct sorted position
            activities.set(j + 1, key);
        }
    }
}

