package supermarket.algorithms;

import supermarket.inventory.Activity;
import supermarket.management.CustomLinkedList;


// This class provides the insertion sort implementation used within the supermarket system.
//
// The method will sort Activity objects by their quantity value, which is required when displaying the last
// four activities for a product in sorted order.
//
// Using the insertion sort is efficient and suitable for the small datasets generated by this project.
//
// Sorting Algorithm coded by Alesha Sangar


public class SortAlgorithm {

    // Sort Activity objects by quantity (ascending) using insertion sort
    public static void insertionSortActivitiesByQuantity(CustomLinkedList<Activity> activities) {

        int n = activities.size(); // number of activities

        if (n <= 1) { // If there is 0 or 1 activity, no sorting is needed
            return; // Exit the method
        }

        // Copy linked list data into a temporary array
        Activity[] temp = new Activity[n];
        for (int i = 0; i < n; i++) {
            temp[i] = activities.get(i);
        }

        // Perform insertion sort on the array
        for (int i = 1; i < n; i++) {

            Activity key = temp[i];   // Current item to insert
            int j = i - 1;

            // Shift elements with larger quantity to the right
            while (j >= 0 && temp[j].getQuantity() > key.getQuantity()) {
                temp[j + 1] = temp[j];
                j--;
            }

            // Insert the key into its correct position
            temp[j + 1] = key;
        }

        // Clear the linked list
        for (int i = 0; i < n; i++) {
            activities.removeFirstElement();
        }

        // Insert sorted elements back into the linked list
        for (int i = 0; i < n; i++) {
            activities.add(temp[i]);
        }
    }

}
